### ISSUE TITLE
Lesson 2 Question 20 problem

### ISSUE THREAD

**Issue by Liv114** [JamesNewton/AdvancedRoboticsWithJavascript#12]
Traceback (most recent call last):
  File "falcon.py", line 96, in 
    sys.stdout.write(formatter.format_results_as_json_string(mode_idx, stack_module.submit_files(), args.show_pretty_submit, stack_module.transform))
  File "/tmp/vmuser_ciimfmskqz/falcon/formatter.py", line 62, in format_results_as_json_string
    results[files.RESULTS_OUT] = transformer(util.get_file_contents(files.RESULTS_OUT))
  File "falcon/stack/js_mocha.py", line 167, in transform
    grading_response = json.loads(eval_output)
  File "/usr/lib/python2.7/json/init.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by JamesNewton** [comment]
See #11
